-- ==============================================================================
-- 요식업 급여 관리 시스템 - Supabase PostgreSQL Schema & Initial Seeds
-- ==============================================================================

-- 1. USERS TABLE
CREATE TABLE IF NOT EXISTS public.users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username TEXT UNIQUE NOT NULL,
  password_hash TEXT NOT NULL,
  email TEXT,
  role TEXT NOT NULL DEFAULT 'ADMIN',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. STORES TABLE
CREATE TABLE IF NOT EXISTS public.stores (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  business_number TEXT,
  biz_number TEXT,
  ceo_name TEXT,
  phone TEXT,
  address TEXT,
  accident_rate NUMERIC DEFAULT 0.9,
  default_break_time_minutes INTEGER DEFAULT 60,
  default_wage_type TEXT DEFAULT 'MONTHLY',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. EMPLOYEES TABLE
CREATE TABLE IF NOT EXISTS public.employees (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  store_id BIGINT NOT NULL REFERENCES public.stores(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  rrn_encrypted TEXT,
  rrn_masked TEXT,
  phone TEXT,
  position TEXT,
  hire_date DATE NOT NULL,
  resign_date DATE,
  employment_type TEXT NOT NULL DEFAULT 'REGULAR',
  wage_type TEXT NOT NULL DEFAULT 'MONTHLY',
  contract_salary BIGINT DEFAULT 0,
  hourly_wage BIGINT DEFAULT 0,
  is_dual_reporting INTEGER DEFAULT 0,
  reported_salary BIGINT DEFAULT 0,
  reported_hourly_wage BIGINT DEFAULT 0,
  dual_reporting_memo TEXT,
  withholding_rate NUMERIC DEFAULT 10.0,
  contract_duration_type TEXT DEFAULT 'ONE_YEAR_OR_MORE',
  is_simple_labor INTEGER DEFAULT 0,
  probation_applicable INTEGER DEFAULT 0,
  probation_start_date DATE,
  probation_end_date DATE,
  probation_rate NUMERIC DEFAULT 90.0,
  dependents_count INTEGER DEFAULT 1,
  bank_name TEXT,
  account_number TEXT,
  is_foreigner INTEGER DEFAULT 0,
  visa_type TEXT,
  fixed_work_hours TEXT,
  has_car INTEGER DEFAULT 0,
  notes TEXT,
  non_taxable_meal INTEGER DEFAULT 0,
  non_taxable_car INTEGER DEFAULT 0,
  non_taxable_overtime INTEGER DEFAULT 0,
  tax_exempt_income_tax INTEGER DEFAULT 1,
  tax_exempt_social_ins INTEGER DEFAULT 1,
  ins_national_pension INTEGER DEFAULT 1,
  ins_health INTEGER DEFAULT 1,
  ins_longterm_care INTEGER DEFAULT 1,
  ins_employment INTEGER DEFAULT 1,
  ins_work_accident INTEGER DEFAULT 1,
  deduct_income_tax INTEGER DEFAULT 1,
  deduct_local_tax INTEGER DEFAULT 1,
  ordinary_wage_items TEXT,
  payslip_display_mode TEXT DEFAULT 'STANDARD',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. ATTENDANCE TABLE
CREATE TABLE IF NOT EXISTS public.attendance (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  employee_id BIGINT NOT NULL REFERENCES public.employees(id) ON DELETE CASCADE,
  store_id BIGINT NOT NULL REFERENCES public.stores(id) ON DELETE CASCADE,
  work_date DATE NOT NULL,
  clock_in TEXT,
  clock_out TEXT,
  break_minutes INTEGER DEFAULT 60,
  net_work_hours NUMERIC DEFAULT 0,
  day_type TEXT,
  regular_hours NUMERIC DEFAULT 0,
  overtime_hours NUMERIC DEFAULT 0,
  night_hours NUMERIC DEFAULT 0,
  holiday_hours NUMERIC DEFAULT 0,
  public_holiday_hours NUMERIC DEFAULT 0,
  holiday_hours_under8 NUMERIC DEFAULT 0,
  holiday_hours_over8 NUMERIC DEFAULT 0,
  public_holiday_hours_under8 NUMERIC DEFAULT 0,
  public_holiday_hours_over8 NUMERIC DEFAULT 0,
  is_public_holiday INTEGER DEFAULT 0,
  is_weekly_holiday INTEGER DEFAULT 0,
  is_annual_leave INTEGER DEFAULT 0,
  is_unpaid_leave INTEGER DEFAULT 0,
  is_absent INTEGER DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(employee_id, work_date)
);

-- 5. PAYROLL RUNS TABLE
CREATE TABLE IF NOT EXISTS public.payroll_runs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  store_id BIGINT NOT NULL REFERENCES public.stores(id) ON DELETE CASCADE,
  year_month TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'DRAFT',
  confirmed_at TIMESTAMPTZ,
  confirmed_by BIGINT REFERENCES public.users(id),
  reopened_at TIMESTAMPTZ,
  reopened_reason TEXT,
  total_payout BIGINT DEFAULT 0,
  total_tax BIGINT DEFAULT 0,
  total_social_ins BIGINT DEFAULT 0,
  snapshot_rates TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(store_id, year_month)
);

-- 6. PAYROLL DETAILS TABLE
CREATE TABLE IF NOT EXISTS public.payroll_details (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  payroll_run_id BIGINT NOT NULL REFERENCES public.payroll_runs(id) ON DELETE CASCADE,
  employee_id BIGINT NOT NULL REFERENCES public.employees(id) ON DELETE CASCADE,
  store_id BIGINT NOT NULL REFERENCES public.stores(id) ON DELETE CASCADE,
  year_month TEXT NOT NULL,
  inspected INTEGER DEFAULT 0,
  basic_pay BIGINT DEFAULT 0,
  overtime_allowance BIGINT DEFAULT 0,
  night_allowance BIGINT DEFAULT 0,
  holiday_allowance BIGINT DEFAULT 0,
  public_holiday_allowance BIGINT DEFAULT 0,
  annual_leave_allowance BIGINT DEFAULT 0,
  weekly_holiday_allowance BIGINT DEFAULT 0,
  attendance_bonus BIGINT DEFAULT 0,
  substitute_allowance BIGINT DEFAULT 0,
  car_allowance BIGINT DEFAULT 0,
  bonus BIGINT DEFAULT 0,
  special_allowance BIGINT DEFAULT 0,
  total_gross_pay BIGINT DEFAULT 0,
  taxable_income BIGINT DEFAULT 0,
  non_taxable_income BIGINT DEFAULT 0,
  national_pension BIGINT DEFAULT 0,
  health_insurance BIGINT DEFAULT 0,
  longterm_care BIGINT DEFAULT 0,
  employment_insurance BIGINT DEFAULT 0,
  income_tax BIGINT DEFAULT 0,
  local_income_tax BIGINT DEFAULT 0,
  attendance_deduction BIGINT DEFAULT 0,
  probation_deduction BIGINT DEFAULT 0,
  unreported_diff_deduction BIGINT DEFAULT 0,
  total_deductions BIGINT DEFAULT 0,
  net_pay BIGINT DEFAULT 0,
  biz_account_pay BIGINT DEFAULT 0,
  personal_account_pay BIGINT DEFAULT 0,
  calculation_breakdown TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(payroll_run_id, employee_id)
);

-- 7. HOLIDAYS TABLE
CREATE TABLE IF NOT EXISTS public.holidays (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  holiday_date DATE NOT NULL UNIQUE,
  holiday_name TEXT NOT NULL,
  is_manual INTEGER DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 8. AUDIT LOGS TABLE
CREATE TABLE IF NOT EXISTS public.audit_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT,
  action TEXT NOT NULL,
  entity_type TEXT NOT NULL,
  entity_id BIGINT,
  details TEXT,
  ip_address TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ==============================================================================
-- INITIAL SEED DATA
-- ==============================================================================

-- Admin User (admin / admin1234!)
INSERT INTO public.users (id, username, password_hash, email, role)
VALUES (1, 'admin', '$2b$10$w0uQo0sI4n468e8mFk3Rk.wNfXgYjWvLqS8Jc.h2m0Gj6J6G2l0G6', 'admin@restaurant.co.kr', 'ADMIN')
ON CONFLICT (id) DO NOTHING;

-- Initial Store
INSERT INTO public.stores (id, name, business_number, biz_number, ceo_name, phone, address, accident_rate, default_break_time_minutes, default_wage_type)
VALUES (1, '신영웅청국장해물뚝배기성서모다아울렛점', '514-12-89012', '514-12-89012', '대표자', '053-585-0000', '대구광역시 달서구 성서공단로 15길', 0.9, 60, 'MONTHLY')
ON CONFLICT (id) DO NOTHING;

-- Initial Employees
INSERT INTO public.employees (
  id, store_id, name, rrn_encrypted, rrn_masked, hire_date, position,
  dependents_count, is_foreigner, employment_type, wage_type, contract_salary, hourly_wage,
  fixed_work_hours, bank_name, account_number, has_car, is_dual_reporting, reported_salary,
  probation_applicable, probation_rate, non_taxable_car
) VALUES 
  (1, 1, '김성향', '711011-2896813', '711011-2896813', '2025-11-01', '팀장', 2, 0, 'REGULAR', 'MONTHLY', 3600000, 11229, '10:00~22:00', '대구은행', '508-12-345678', 1, 1, 2156880, 0, 90.0, 1),
  (2, 1, '김성훈', '770315-1823045', '770315-1823045', '2025-12-24', '과장', 4, 0, 'REGULAR', 'MONTHLY', 3600000, 11229, '10:00~22:00', '국민은행', '456-78-901234', 1, 0, 3850530, 0, 90.0, 1),
  (3, 1, '김혜숙', '660824-2525110', '660824-2525110', '2025-11-01', '사원', 1, 0, 'REGULAR', 'MONTHLY', 3260000, 10320, '10:00~22:00', '우리은행', '1002-345-678901', 0, 1, 2156880, 0, 90.0, 0),
  (4, 1, '김순자', '670119-2330927', '670119-2330927', '2025-11-10', '사원', 1, 0, 'REGULAR', 'MONTHLY', 1986020, 10320, '10:00~15:00', '하나은행', '234-910234-56789', 0, 0, 1986020, 0, 90.0, 0),
  (5, 1, '정용주', '730725-1526520', '730725-1526520', '2026-07-02', '수습 사원', 3, 0, 'REGULAR', 'MONTHLY', 3011782, 9288, '10:00~22:00', '카카오뱅크', '3333-01-9283741', 1, 0, 0, 1, 90.0, 1),
  (6, 1, '차이수', '650420-2772829', '650420-2772829', '2026-07-19', '수습 사원', 1, 0, 'REGULAR', 'MONTHLY', 3011782, 9288, '09:00~21:00', '토스뱅크', '1000-0192-8374', 0, 0, 0, 1, 90.0, 0)
ON CONFLICT (id) DO NOTHING;

-- 2026 Statutory Public Holidays
INSERT INTO public.holidays (holiday_date, holiday_name, is_manual) VALUES
  ('2026-01-01', '신정', 0),
  ('2026-02-16', '설날 연휴', 0),
  ('2026-02-17', '설날', 0),
  ('2026-02-18', '설날 연휴', 0),
  ('2026-03-01', '3·1절', 0),
  ('2026-05-05', '어린이날', 0),
  ('2026-05-24', '부처님오신날', 0),
  ('2026-06-06', '현충일', 0),
  ('2026-08-15', '광복절', 0),
  ('2026-09-24', '추석 연휴', 0),
  ('2026-09-25', '추석', 0),
  ('2026-09-26', '추석 연휴', 0),
  ('2026-10-03', '개천절', 0),
  ('2026-10-09', '한글날', 0),
  ('2026-12-25', '기독탄신일(성탄절)', 0)
ON CONFLICT (holiday_date) DO NOTHING;
